# Generated by Django 4.2 on 2024-08-17 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_type', models.IntegerField(choices=[(1, 'INCOME'), (2, 'EXPENSE')], default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('transaction_id', models.UUIDField()),
                ('user_email', models.CharField(blank=True, max_length=40, null=True)),
                ('status', models.IntegerField(choices=[(1, 'COMPLETED'), (2, 'FAILURE'), (3, 'INITIATED'), (4, 'PENDING')], default=4)),
                ('_from', models.CharField(blank=True, max_length=100, null=True)),
                ('to', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_method', models.IntegerField(choices=[(1, 'ESEWA'), (2, 'KHALTI'), (3, 'ADMIN')])),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
